name: GCC CICD

on:
  push:
  workflow_dispatch:
    inputs:
      customver:
        description: 'Set custom GCC version (default: 15.1.0)'
        required: true
        default: '15.1.0'

env:
  VERSION: ${{ github.event.inputs.customver || '15.1.0' }}
jobs:
  build:
    runs-on: windows-2025
    permissions:
      contents: write
    steps:
      - name: Get build script
        uses: actions/checkout@v4
        with:
          repository: 'niXman/mingw-builds'
          ref: 'develop'
      - name: Get patch
        uses: actions/checkout@v4
        with:
          path: mypatch
      - name: Apply patch to build script
        shell: cmd
        run: 'git apply -v mypatch\log_location.patch'
      - name: Checking CPU architecture (for tuning and possible compile error)
        shell: pwsh
        run: 'Get-WmiObject Win32_Processor'
      - name: build
        shell: C:\shells\msys2bash.cmd {0}
        run: >-
          ./build
          --mode=gcc-${{ env.VERSION }}
          --buildroot=/c/gcc
          --jobs=4
          --rev=${{ github.run_number }}
          --with-default-msvcrt=ucrt
          --rt-version=v12.0.0
          --threads=mcf
          --exceptions=seh
          --arch=x86_64
          --bin-compress
          --enable-languages=c,c++
          --no-extras
          --no-gcc-lto
          --cflags='-mtune=skylake'
          --cxxflags='-mtune=skylake'
      - name: Upload result
        uses: ncipollo/release-action@v1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          tag: b${{ github.run_number }}.${{ env.VERSION }}
          artifacts: c:/gcc/archives/*.7z
          artifactContentType: application/x-7z-compressed
          body: "GCC release build"
          prerelease: true
          allowUpdates: true
          artifactErrorsFailBuild: true
